name: Test Commit

on:
  push:
    branches: "**"
        
jobs:
  test:
    strategy:
      matrix:
        go_version: ['13', '14', '15', '16', '17', '18', '19', '20', '21', '22']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '~1.${{ matrix.go_version }}.0'
    
    - name: Run Tests
      run: go test ./...
